{
    "6": {
        "original": {
            "paperID": "6348c3490aa17188229decfd09b67e5169ce1cfc",
            "paperName": "Database indexing for production MegaBLAST searches",
        },
        "citation": {
            "paperID": "a6e9e9a5c1ff99472f3ba5a066fce18d277df148",
            "paperName": "GENOOGLE: AN INDEXED AND PARALLELIZED SEARCH ENGINE FOR SIMILAR DNA SEQUENCES",
        },
        "context match": "6/6",
        "common references": {
            "r1": {
                "paperID": "02613d6e3ecf67ed9ae8ce67a35a92f3986bc4cf",
                "paperName": "BLAST (Altschul et al., 1997) is a package of programs to match a query biological sequence against a database and identify database sequences that have statistically significant local alignments with a part of the query.",
                "original citing context": "Then, more complex networks were proposed to handle the LDCT denoising problem such as the wavelet network",
                "citation citing context": "Among the al-gorithms which use heuristics for similar sequences searching, the FASTA [23] and BLAST [1, 2, 5] algorithms are the more used and know algorithms. These algo-rithms search for areas which has similarities, called HSP (High Scoring Pairs), and then, they make the alignment of the best HSP found using a dynamic programming algorithm",
                "match or not": True,
            },
            "r2": {
                "paperID": "d3fd86b5e929ebd05328e5518ae693bdca153fde",
                "paperName": "SSAHA: a fast search method for large DNA databases.",
                "original citing context": "Two widely used software packages that do preprocess the database for biological sequence comparison are SSAHA (Ning et al., 2001) and BLAT (Kent, 2002).",
                "citation citing context": "Some similar search-ing sequences techniques that uses vectors as inverted indexes are: SSAHA[22], BLAT [15], PatternHunter [17] the miBLAST [16], Megablast [25], MegaBlast [18], and Kalafus [14] which uses hash tables to align whole genomes",
                "match or not": True,
            },
            "r3": {
                "paperID": "2ba767ef140727c9554f14117367a55355323186",
                "paperName": "SSAHA: a fast search method for large DNA databases.",
                "original citing context": "Another possible improvement is that long singly linked lists of k-mers could be replaced by a more sophisticated structure such as a hash table or some sort of tree (Giladi et al., 2002).",
                "citation citing context": "One example of suffixes tress application is presented by [10], where an algorithm for building tree to find near-exact sequences is utilized.",
                "match or not": True,
            },
            "r4": {
                "paperID": "bbb3dc003d0a9770f6d4f93be8c12aba94037ff5",
                "paperName": "miBLAST: scalable evaluation of a batch of nucleotide sequence queries with BLAST",
                "original citing context": "... is miBLAST (Kim et al., 2005). miBLAST was designed for short queries of under 100 bases and we confirm that its relative performance does deteriorate for longer queries",
                "citation citing context": "Some similar search-ing sequences techniques that uses vectors as inverted indexes are: SSAHA[22], BLAT [15], PatternHunter [17] the miBLAST [16], Megablast [25], MegaBlast [18], and Kalafus [14] which uses hash tables to align whole genomes",
                "match or not": True,
            },
            "r5": {
                "paperID": "2878976835c73ed0906e17a7336b9bf10d491a1a",
                "paperName": "BLAT--the BLAST-like alignment tool.",
                "original citing context": "Two widely used software packages that do preprocess the database for biological sequence comparison are SSAHA (Ning et al., 2001) and BLAT (Kent, 2002).",
                "citation citing context": "Some similar search-ing sequences techniques that uses vectors as inverted indexes are: SSAHA[22], BLAT [15], PatternHunter [17] the miBLAST [16], Megablast [25], MegaBlast [18], and Kalafus [14] which uses hash tables to align whole genomes",
                "match or not": True,
            },
            "r6": {
                "paperID": "261c2bbe4a4fa84ce1958333456080ce6af8a949",
                "paperName": "Survey on index based homology search algorithms",
                "original citing context": "Numerous research studies, recently reviewed in Jiang et al. (2007), suggest that preprocessing the database and searching a database-derived data structure can yield much faster search times.",
                "citation citing context": " Transforming based methods are considered out of the scope of this work, but Jing [13] presents methods that use this technique",
                "match or not": True,
            },
        },
    },
    "7": {
        "original": {
            "paperID": "ae93d816819d4a6a6e18eb09bbb51218a97441a7",
            "paperName": "A multiple Lyapunov function approach to stabilization of fuzzy control systems",
        },
        "citation": {
            "paperID": "96ce933d2927e5d39cc81c1dc2b60a89254c1411",
            "paperName": "A Survey on Analysis and Design of Model-Based Fuzzy Control Systems",
        },
        "context match": "3/7",
        "common references": {
            "r1": {
                "paperID": "d1f58bfbc23c04b127e39040d1f2e4c8f725328d",
                "paperName": "Stability analysis and design for a class of continuous-time fuzzy control systems",
                "original citing context": "Recently, piecewise Lyapunov function approaches have received increasing attention as they attempt to relax the conservativeness of stability and stabilization problems, e.g., [24] and [25].",
                "citation citing context": "The first category of methods is proposed in the earlier stage of developments [24], [25], [30], [80], [133]",
                "match or not": True,
            },
            "r2": {
                "paperID": "d43ec586074bb51cf4cbe71f350cd5294b020d58",
                "paperName": "Analysis and design for a class of complex control systems part II: Fuzzy controller design",
                "original citing context": "Recently, piecewise Lyapunov function approaches have received increasing attention as they attempt to relax the conservativeness of stability and stabilization problems, e.g., [24] and [25].",
                "citation citing context": "T–S fuzzy model [265], also called the Type-III fuzzy model by Sugeno [259], is in fact a fuzzy dynamic model [25], [28], [29].",
                "match or not": False,
            },
            "r3": {
                "paperID": "233b79c15588c8b35c17d26515a93c19a5ee092c",
                "paperName": "An approach to fuzzy control of nonlinear systems: stability and design issues",
                "original citing context": "*Not cited",
                "citation citing context": "The third category of methods is most popular to date [2], [3], [6], [12], [33]–[37], [40], [42], [46], [47], [56], [61], [109], [110], [112], [115], [119], [125], [130], [140]–[144], [147], [148], [151], [159], [167], [168], [175], [181], [183], [191], [192], [195], [197], [198], [206], [214], [221], [239], [267]–[269], [273], [275], [276], [282]–[286], [293], [302]–[304], [312], [317], [322], [323], [327].",
                "match or not": False,
            },
            "r4": {
                "paperID": "d79eeb61bc8960242550234e7a801d6863c58aec",
                "paperName": "Fuzzy identification of systems and its applications to modeling and control",
                "original citing context": "*Not cited",
                "citation citing context": "T–S fuzzy model [265], also called the Type-III fuzzy model by Sugeno [259], is in fact a fuzzy dynamic model [25], [28], [29]. ",
                "match or not": False,
            },
            "r5": {
                "paperID": "46a16d3648aa719abaf319b7ca474cfde62f76e4",
                "paperName": "Linear Matrix Inequalities in Systems and Control Theory",
                "original citing context": "*Not cited",
                "citation citing context": "The equivalence of (4.4) and (4.5) can be easily established by using the Schur complement together with X = P-1[19]. ",
                "match or not": False,
            },
            "r6": {
                "paperID": "fc1655950f15998c6b6df16cecd1949c414b8d6f",
                "paperName": "On stability of fuzzy systems expressed by fuzzy rules with singleton consequents",
                "original citing context": "STABILITY and design issues of fuzzy control systems have been discussed in an extensive literature, e.g., [1]–[12], [15]–[18]. ",
                "citation citing context": "This can be witnessed by a number of excellent books and tutorial articles on the topic; see, for example, [7], [164], [165], [210], [236], [240], [241], [251], [259], [269], [299], [300], and [318]. ",
                "match or not": True,
            },
            "r7": {
                "paperID": "acc61ba8df77ea48ddf74c9bbfe3eecb9ed1facf",
                "paperName": "Stability analysis of discrete fuzzy control system",
                "original citing context": "STABILITY and design issues of fuzzy control systems have been discussed in an extensive literature, e.g., [1]–[12], [15]–[18]. ",
                "citation citing context": "The typical approaches include describing function approach [136], cell-state transition [132], Lure’s system approach [59], [208], Popov’s theorem [91], circle criterion [226], [244], [252], conicity criterion [69], sliding mode control [120], and hyperstability [21], [226], among others",
                "match or not": True,
            },
        },
    },
    "8": {
        "original": {
            "paperID": "ae93d816819d4a6a6e18eb09bbb51218a97441a7",
            "paperName": "A multiple Lyapunov function approach to stabilization of fuzzy control systems",
        },
        "citation": {
            "paperID": "a8357bca7d2f761822d63f4ab2a9b4215f04d3d6",
            "paperName": "Fuzzy control system designs using redundancy of descriptor representation: a fuzzy Lyapunov function approach",
        },
        "context match": "6/8",
        "common references": {
            "r1": {
                "paperID": "23e5f9838c563072551bdec2e7073f470dab9c71",
                "paperName": "A study on coincidence of symbolic and continuous behavior for symbolic stability analysis",
                "original citing context": "STABILITY and design issues of fuzzy control systems have been discussed in an extensive literature, e.g., [1]–[12], [15]–[18]. ",
                "citation citing context": "Nonlinear control based on the Takagi-Sugeno fuzzy model [1] has received a lot of attention over the last decade (e.g., see [2]- [11]).",
                "match or not": True,
            },
            "r2": {
                "paperID": "2f796e60e5fbe37cc1493569293e4d2da8b949e6",
                "paperName": "Stability analysis of the fuzzy logic controller designed by the phase portrait assignment algorithm",
                "original citing context": "STABILITY and design issues of fuzzy control systems have been discussed in an extensive literature, e.g., [1]–[12], [15]–[18]. ",
                "citation citing context": "Nonlinear control based on the Takagi-Sugeno fuzzy model [1] has received a lot of attention over the last decade (e.g., see [2]- [11]).",
                "match or not": True,
            },
            "r3": {
                "paperID": "331ace8e416d66e4187b4158456515a7add3f0b7",
                "paperName": "Fuzzy Control Systems Design and Analysis: A Linear Matrix Inequality Approach",
                "original citing context": "*Not cited",
                "citation citing context": "An advantage of the fuzzy model-based control [12] is to provide a natural, simple and effective design approach although other nonlinear control techniques [13] require special and rather involved knowledge",
                "match or not": False,
            },
            "r4": {
                "paperID": "cf248d689c8bae58461073f6dfd94cb1bd19a43e",
                "paperName": "Back-driving a truck with suboptimal distance trajectories: a fuzzy logic control approach",
                "original citing context": "STABILITY and design issues of fuzzy control systems have been discussed in an extensive literature, e.g., [1]–[12], [15]–[18]. ",
                "citation citing context": "Nonlinear control based on the Takagi-Sugeno fuzzy model [1] has received a lot of attention over the last decade (e.g., see [2]- [11]).",
                "match or not": True,
            },
            "r5": {
                "paperID": "17dfde993c4b6fdabe06cf87c8ef2fe143f61f73",
                "paperName": "Algebraic design of fuzzy logic controllers",
                "original citing context": "STABILITY and design issues of fuzzy control systems have been discussed in an extensive literature, e.g., [1]–[12], [15]–[18]. ",
                "citation citing context": "Nonlinear control based on the Takagi-Sugeno fuzzy model [1] has received a lot of attention over the last decade (e.g., see [2]- [11]).",
                "match or not": True,
            },
            "r6": {
                "paperID": "d79eeb61bc8960242550234e7a801d6863c58aec",
                "paperName": "Fuzzy identification of systems and its applications to modeling and control",
                "original citing context": "*Not cited",
                "citation citing context": "Nonlinear control based on the Takagi-Sugeno fuzzy model [1] has received a lot of attention over the last decade (e.g., see [2]- [11]).",
                "match or not": False,
            },
            "r7": {
                "paperID": "c070cac4200575ae537e1965f0fbf99d204faee8",
                "paperName": "Synthesis of an LMI-based fuzzy control system with guaranteed optimal H/sub /spl infin// performance",
                "original citing context": "STABILITY and design issues of fuzzy control systems have been discussed in an extensive literature, e.g., [1]–[12], [15]–[18]. ",
                "citation citing context": "Nonlinear control based on the Takagi-Sugeno fuzzy model [1] has received a lot of attention over the last decade (e.g., see [2]- [11]).",
                "match or not": True,
            },
            "r8": {
                "paperID": "fc1655950f15998c6b6df16cecd1949c414b8d6f",
                "paperName": "On stability of fuzzy systems expressed by fuzzy rules with singleton consequents",
                "original citing context": "STABILITY and design issues of fuzzy control systems have been discussed in an extensive literature, e.g., [1]–[12], [15]–[18]. ",
                "citation citing context": "Nonlinear control based on the Takagi-Sugeno fuzzy model [1] has received a lot of attention over the last decade (e.g., see [2]- [11]).",
                "match or not": True,
            },
        },
    },
    "11": {
        "original": {
            "paperID": "125246099c1a21469af6735480bae2c426c31cd5",
            "paperName": "Low Dose CT Image Denoising Using a Generative Adversarial Network with Wasserstein Distance and Perceptual Loss",
        },
        "citation": {
            "paperID": "f571725ffc18c6249702ab457b287495302a4e68",
            "paperName": "A survey of generative adversarial networks",
        },
        "context match": "8/11",
        "common references": {
            "r1": {
                "paperID": "6364fdaa0a0eccd823a779fcdd489173f938e91a",
                "paperName": "U-Net: Convolutional Networks for Biomedical Image Segmentation",
                "original citing context": "Then, more complex networks were proposed to handle the LDCT denoising problem such as the U-shape network in [25], [26] and the wavelet network in [27].",
                "citation citing context": "Then deep convolutional GANs (DCGANs)[8] are created by replacing the pooling layers with strided convolutions and fractional-strided convolutions and successfully applying batch normalization on both the generator and the discriminator. Isola et al.[9] improve CGANs by using U-net[10] based structure as the generator and a convolutional markovian discriminator to deal with image-to-image translation(pix2pix). ",
                "match or not": False,
            },
            "r2": {
                "paperID": "fc7822f56dd255a872326b9536a0821bbf0277dd",
                "paperName": "Generative Visual Manipulation on the Natural Image Manifold",
                "original citing context": "Up to now, GANs have been used in many applications such as single image super-resolution [28], art creation [33], [34], and image transformation [35]",
                "citation citing context": "Image editing: GANs could be used to learn directly the image manifold with defined editing operations to manipulate images[75]",
                "match or not": True,
            },
            "r3": {
                "paperID": "ef6abdcbd0871cb356e8669b6cdb31ed8b013cc2",
                "paperName": "Medical Image Synthesis with Context-Aware Generative Adversarial Networks",
                "original citing context": " In the field of medical imaging, Nie et al. proposed to use GAN to estimate CT image from its corresponding MR image [36]",
                "citation citing context": "GANs could also be applied to image blending[23], colorization[79, 80], medical analysis[81, 82], image de-raining[83], color correction[84], CT image denoising[85, 86], semantic segmentation[87, 88], galaxy images recover[89], magnetic resonance imaging(MRI) to computed tomography(CT)[90]etc.",
                "match or not": True,
            },
            "r4": {
                "paperID": "c68796f833a7151f0a63d1d1608dc902b4fdc9b6",
                "paperName": "GENERATIVE ADVERSARIAL NETS",
                "original citing context": " While the G network is trained to produce realistic images G(z) from a random vector z, the D network is trained to discriminate between real and generated images [31], [32]",
                "citation citing context": "GANs contain two networks[1], a generator G and a discriminator D",
                "match or not": True,
            },
            "r5": {
                "paperID": "9a700c7a7e7468e436f00c34551fbe3e0f70e42f",
                "paperName": "Towards Principled Methods for Training Generative Adversarial Networks",
                "original citing context": "Despite its success in these areas, GANs still suffer from a remarkable difficulty in training [32], [37]",
                "citation citing context": "Another problem in GANs is the mode collapse which drastically destroys the generated samples diversity. Arjovsky et al.[11] substantiate that GANs’ problems of unstable behavior of training and mode collapse is due to that the distribution’s support of real and generated data has a nonnegligible intersection.",
                "match or not": True,
            },
            "r6": {
                "paperID": "df0c54fe61f0ffb9f0e36a17c2038d9a1964cba3",
                "paperName": "Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network",
                "original citing context": "As revealed by the recent work [28], [29], this per- pixel MSE is often associated with over-smoothed edges and loss of details.",
                "citation citing context": "Super resolution: Super-resolution GANs(SRGANs) employ a deep residual network(ResNet) with skip-connection and a pretrained visual geometry group(VGG) network[34].",
                "match or not": False,
            },
            "r7": {
                "paperID": "8acbe90d5b852dadea7810345451a99608ee54c7",
                "paperName": "Image-to-Image Translation with Conditional Adversarial Networks",
                "original citing context": "Up to now, GANs have been used in many applications such as single image super-resolution [28], art creation [33], [34], and image transformation [35]",
                "citation citing context": "Besides pix2pix[9], coupleld GANs(CoGANs) [63] could also be applied to image transformation",
                "match or not": True,
            },
            "r8": {
                "paperID": "1dcda6ac3fd33bf938574aca9542aec5e5cace26",
                "paperName": "Neural Photo Editing with Introspective Adversarial Networks",
                "original citing context": "Up to now, GANs have been used in many applications such as single image super-resolution [28], art creation [33], [34], and image transformation [35]",
                "citation citing context": "VAE could also be hybridized to GANs[76] to achieve accurate reconstruction",
                "match or not": True,
            },
            "r9": {
                "paperID": "edf73ab12595c6709f646f542a0d2b33eb20a3f4",
                "paperName": "Improved Training of Wasserstein GANs",
                "original citing context": "After that, an improved WGAN with gradient penalty was proposed [38] to accelerate the convergence.",
                "citation citing context": "Then some methods are innovated to bypass this problem. Improved WGANs are proposed, which use gradient penalty(WGAN-GP)[14] to enforce the Lipschitz constraint, rather than the weight clipping. ",
                "match or not": True,
            },
            "r10": {
                "paperID": "2f85b7376769473d2bed56f855f115e23d727094",
                "paperName": "Wasserstein GAN",
                "original citing context": "Consequently, Martin et al. proposed to use the Earth-Mover (EM) distance or Wasserstein metric between the generated image samples and real data for GAN [30],",
                "citation citing context": "Wasserstein GANs(WGANs)[13] are proposed by using the Earth-Mover distance to estimate the objective function, instead of the Jensen-Shannon divergence. ",
                "match or not": True,
            },
            "r11": {
                "paperID": "11a8dcaec7a7751a9e240440267c5773fc7faefa",
                "paperName": "Generative Adversarial Networks for Noise Reduction in Low-Dose CT",
                "original citing context": "*Does not exist",
                "citation citing context": "*Not cited",
                "match or not": False,
            },
        },
    },
    "12": {
        "original": {
            "paperID": "125246099c1a21469af6735480bae2c426c31cd5",
            "paperName": "Low Dose CT Image Denoising Using a Generative Adversarial Network with Wasserstein Distance and Perceptual Loss",
        },
        "citation": {
            "paperID": "361caa519ca1784853d71bcc9e9ee76414daea1b",
            "paperName": "A review on Deep Learning approaches for low-dose Computed Tomography restoration",
        },
        "context match": "7/12",
        "common references": {
            "r1": {
                "paperID": "6364fdaa0a0eccd823a779fcdd489173f938e91a",
                "paperName": "U-Net: Convolutional Networks for Biomedical Image Segmentation",
                "original citing context": "Then, more complex networks were proposed to handle the LDCT denoising problem such as the U-shape network in [25], [26] and the wavelet network in [27].",
                "citation citing context": "Ronneberger et al. [56] have proposed the U-net model, which consists of symmetric architecture constructed by a contracting path and expanding path",
                "match or not": True,
            },
            "r2": {
                "paperID": "5bc52b33c3a0555025c9bc1a71eb533cd2702bbc",
                "paperName": "A deep convolutional neural network using directional wavelets for low‐dose X‐ray CT reconstruction",
                "original citing context": "Then, more complex networks were proposed to handle the LDCT denoising problem such as the U-shape network in [25], [26] and the wavelet network in [27].",
                "citation citing context": "Among them, the AAPM-Net model in [36] has been developed based on the high-frequency channels obtained after contourlet transformation on the LDCT images.",
                "match or not": True,
            },
            "r3": {
                "paperID": "603bb905322c80725dab75b4343a78325c662d66",
                "paperName": "Low-Dose CT With a Residual Encoder-Decoder Convolutional Neural Network",
                "original citing context": "Typically, a mean squared error (MSE) loss function is used, which tries to minimize pixel-wise errors between generated and ground truth images [24], [41],",
                "citation citing context": "Based on that, later, Chen et al. [3] have published an RED-CNN model by combining autoencoder with CNN for LDCT restoration.",
                "match or not": False,
            },
            "r4": {
                "paperID": "a6cb366736791bcccc5c8639de5a8f9636bf87e8",
                "paperName": "Adam: A Method for Stochastic Optimization",
                "original citing context": "In our experiments, all the networks were optimized using Adam algorithm [44]. ",
                "citation citing context": "In LDCT restoration applications, the learning rate is associated with the well-known optimizers such as Stochastic Gradient Descent, ADAM [39], and limited memory BFGS [40] algorithm. ",
                "match or not": True,
            },
            "r5": {
                "paperID": "f5def96246b83e4bdfb3f21668f0038715732a02",
                "paperName": "Projection space denoising with bilateral filtering and CT noise modeling for dose reduction in CT.",
                "original citing context": "These methods generally fall into three categories: (a) sinogram filtration before reconstruction [3]–[5], (b) iterative reconstruction [6], [7], and (c) image post-processing after reconstruction [8]–[10]",
                "citation citing context": "Structural adaptive fltering [37, 70], bilateral fltering [47], and penalized likelihood method [68] are the popular sinogram domain fltering methods",
                "match or not": True,
            },
            "r6": {
                "paperID": "d2493cc3887afb1e49d5bd9c494345db0ee6b8f5",
                "paperName": "Low-Dose X-ray CT Reconstruction via Dictionary Learning",
                "original citing context": "Popular image priors include variation (TV) and its variants [16]–[18], as well as dictionary learn- ing [19], [20]. ",
                "citation citing context": "ction by iterating between the sinogram and image domain. Non-local means [5], total variation [89], dictionary learning [74], and lowrank approximation [2] are some of the priors used within the iterative reconstruction-based restoration category",
                "match or not": True,
            },
            "r7": {
                "paperID": "412b3ef02c85087e5f1721176114672c722b17a4",
                "paperName": "A Taxonomy of Deep Convolutional Neural Nets for Computer Vision",
                "original citing context": "Following the common practice in the deep learning community [42], small 3 × 3 kernels were used in each convolutional layer.",
                "citation citing context": "Due to the recent advancement in high-performance computing and hardware resources, CNN-based denoising applications have popular in medical imaging [65]",
                "match or not": False,
            },
            "r8": {
                "paperID": "8acbe90d5b852dadea7810345451a99608ee54c7",
                "paperName": "Image-to-Image Translation with Conditional Adversarial Networks",
                "original citing context": "Up to now, GANs have been used in many applications such as single image super-resolution [28], art creation [33], [34], and image transformation [35]",
                "citation citing context": "However, after publishing the Pix-to-Pix GAN by Isola et al. [31], there were several LDCT restoration applications published based on it.",
                "match or not": True,
            },
            "r9": {
                "paperID": "d2c733e34d48784a37d717fe43d9e93277a8c53e",
                "paperName": "ImageNet: A large-scale hierarchical image database",
                "original citing context": "This is because the VGG loss used in CNN-VGG and WGAN-VGG is computed in a feature space that is trained previously on a very large natural image dataset [46].",
                "citation citing context": "After the publishing of the image net [9] pre-trained networks, namely VGG-16 and VGG19 [63], the perceptual loss has been introduced to the DL model optimization to overcome the issues raised by both the MSE and LAE.",
                "match or not": False,
            },
            "r10": {
                "paperID": "edf73ab12595c6709f646f542a0d2b33eb20a3f4",
                "paperName": "Improved Training of Wasserstein GANs",
                "original citing context": "After that, an improved WGAN with gradient penalty was proposed [38] to accelerate the convergence.",
                "citation citing context": "Thus, inspired by [1] and [25], the Wasserstein distance with the gradient penalty has been introduced as the loss function to overcome the identifed convergence issues [35, 42, 77].",
                "match or not": True,
            },
            "r11": {
                "paperID": "11a8dcaec7a7751a9e240440267c5773fc7faefa",
                "paperName": "Generative Adversarial Networks for Noise Reduction in Low-Dose CT",
                "original citing context": "*Does not exist",
                "citation citing context": "Vanilla GAN represents the simplest GAN model as depicted in Fig. 11a. Wolterink et al. [72] have frst applied the GAN for resolving the limitation of voxel-wise regression in LDCT noise reduction.",
                "match or not": False,
            },
            "r12": {
                "paperID": "eb42cf88027de515750f230b23b1a057dc782108",
                "paperName": "Very Deep Convolutional Networks for Large-Scale Image Recognition",
                "original citing context": "In our implementation, we adopt the well-known pre-trained VGG-19 network [40] as the feature extractor.",
                "citation citing context": "After the publishing of the image net [9] pre-trained networks, namely VGG-16 and VGG19 [63], the perceptual loss has been introduced to the DL model optimization to overcome the issues raised by both the MSE and LAE",
                "match or not": False,
            },
        },
    },
}
